---
# Deploy tools not found in the Kali repositories
- hosts: all
  become: true
  tasks:
    # Install VSCode
    - name: Install MS Visual Studio Code
      ansible.builtin.include_role:
        name: "ansible-role-vscode"

    # Clone git repos
    - name: Clone git repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "/opt/{{ item.name }}"
        version: "{{ item.version | default('master') }}"
        depth: 1
        force: true
      loop: "{{ git_repos | flatten(levels=1) }}"

    # Download miscellaneous tools
    - name: Ensure destination directory exists for miscellaneous tools
      ansible.builtin.file:
        path: "{{ item.dest | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop: "{{ misc_downloads }}"
            
    - name: Download miscellaneous tools
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest | dirname }}/{{ item.url | basename }}"
        owner: root
        group: root
        mode: "{{ item.mode | default('0755') }}"
      loop: "{{ misc_downloads }}"

    # Install, configure, and link tools to /usr/local/bin
    - name: Install Eavesarp
      ansible.builtin.command: chdir=/opt/eavesarp {{ item }}
      with_items:
        - "python3 -m pip install -r requirements.txt"
    - name: Link Eavesarp
      ansible.builtin.file:
        src: "/opt/eavesarp/eavesarp.py"
        dest: "/usr/local/bin/eavesarp"
        state: link
        mode: 0755
    - name: Link PCredz
      ansible.builtin.file:
        src: "/opt/pcredz/Pcredz"
        dest: "/usr/local/bin/pcredz"
        state: link
        mode: 0755
    - name: Link Unicorn
      ansible.builtin.file:
        src: "/opt/unicorn/unicorn.py"
        dest: "/usr/local/bin/unicorn"
        state: link
    - name: Build Qmodbus
      ansible.builtin.command: "{{ item }}"
      loop:
        - mkdir -p /opt/qmodbus/build
        - qmake /opt/qmodbus -o /opt/qmodbus/build/Makefile
        - make --directory=/opt/qmodbus/build
      tags: qmodbus
    - name: Link Qmodbus
      ansible.builtin.file:
        src: "/opt/qmodbus/build/qmodbus"
        dest: "/usr/local/bin/qmodbus"
        state: link
        mode: 0755
      tags: qmodbus
    - name: Link nxc
      ansible.builtin.file:
        src: "/opt/netexec/nxc"
        dest: "/usr/local/bin/nxc"
        state: link
        mode: 0755
    - name: Install Obsidian
      ansible.builtin.command: chdir=/opt/obsidian {{ item }}
      with_items:
        - "sudo apt install obsidian_1.4.16_amd64.deb"
      tags: obsidian
