---
# Deploy tools not found in the Kali repositories
- hosts: all
  become: true
  tasks:
  # Install VSCode
    - name: Install MS Visual Studio Code
      ansible.builtin.include_role:
        name: "ansible-role-vscode"

# Clone git repos
    - name: Clone git repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "/opt/{{ item.name }}"
        version: "{{ item.version | default('master') }}"
        depth: 1
        force: true
      loop: "{{ git_repos | flatten(levels=1) }}"

# Clone wordlist repos
    - name: Clone wordlist repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "/usr/share/wordlists/{{ item.name }}"
        version: "{{ item.version | default('master') }}"
        depth: 1
        force: true
      loop: "{{ wordlist_repos | flatten(levels=1) }}"

    # Miscellaneous tools
    - name: Ensure destination directory exists
      ansible.builtin.file:
        dest: "{{ item.dest | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop: "{{ misc_downloads }}"
            
    - name: Download files
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode | default('0755') }}"
      loop: "{{ misc_downloads }}"

# Install, configure, and link tools to /usr/local/bin
    - name: Install Eavesarp
      ansible.builtin.command: chdir=/opt/eavesarp {{ item }}
      with_items:
        - "python3 -m pip install -r requirements.txt"
    - name: Link Eavesarp
      ansible.builtin.file:
        src: "/opt/eavesarp/eavesarp.py"
        dest: "/usr/local/bin/eavesarp"
        state: link
        mode: 0755
    - name: Link PCredz
      ansible.builtin.file:
        src: "/opt/pcredz/Pcredz"
        dest: "/usr/local/bin/pcredz"
        state: link
        mode: 0755
    - name: Link Unicorn
      ansible.builtin.file:
        src: "/opt/unicorn/unicorn.py"
        dest: "/usr/local/bin/unicorn"
        state: link