---
# Set as the user account that runs the ansible playbook
kali_user: "{{ lookup('env','USER') }}"

# Burp Suite settings
burpsuite_cacert_path: "{{ burpsuite_extras_dir }}/PortSwigger_CA.der"
burpsuite_extras_dir: "/home/{{ kali_user }}/BurpSuiteExtras"
burpsuite_user: "{{ kali_user }}"

# Git repositories for projects that are either not in Kali or are updated more frequently than Kali repos
git_repos:
  - name: privilege-escalation-awesome-scripts-suite
    repo: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite.git
  - name: quieter-firefox
    repo: https://bitbucket.org/mrbbking/quieter-firefox.git
  - name: eavesarp
    repo: https://github.com/metaver5o/eavesarp.git
  - name: pcredz
    repo: https://github.com/lgandx/PCredz.git
  - name: unicorn
    repo: https://github.com/trustedsec/unicorn.git

wordlist_repos:    
  - name: SecLists
    repo: https://github.com/danielmiessler/SecLists.git
  - name: Probable-Wordlists
    repo: https://github.com/berzerk0/Probable-Wordlists.git
  - name: statistically-likely-usernames
    repo: https://github.com/insidetrust/statistically-likely-usernames.git

# Vars for additional Kali packages
kali_packages:
  - ansible-core
  - awscli
  - bettercap
  - bloodhound
  - cmake
  - covenant-kbx
  - dnsmasq
  - docker.io
  - docker-compose
  - eyewitness
  - gdb
  - gdbserver
  - ghidra
  - gobuster
  - golang
  - hcxtools
  - htop
  - jq
  - mosh
  - net-tools
  - nfs-kernel-server
  - patator
  - powershell
  - powershell-empire
  - python3-dev
  - python3-pip
  - python-is-python3
  - kali-linux-default
  - keepassxc
  - libgcrypt-dev
  - libreoffice
  - libssl-dev
  - libpcap-dev
  - nbtscan-unixwiz
  - ncat
  - neo4j
  - openjdk-11-jdk
  - parallel
  - payloadsallthethings
  - realtek-rtl88xxau-dkms
  - remmina
  - rlwrap
  - seclists
  - scite
  - starkiller
  - testssl.sh
  - tmux
  - ufw
  - wireguard
  - xclip
  - xsel

# Vars for miscellaneous tools  
misc_downloads:
  - url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy32s
    dest: /opt/pspy32s
  - url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64s
    dest: /opt/pspy64s
  - url: https://download.sysinternals.com/files/SysinternalsSuite.zip
    dest: /usr/share/windows-binaries
  - url: https://github.com/carlospolop/PEASS-ng/releases/download/20220417/winPEAS.bat
    dest: /opt/privesc
  - url: https://github.com/carlospolop/PEASS-ng/releases/download/20220417/winPEASx64.exe
    dest: /usr/local/windows-binaries
  - url: https://github.com/carlospolop/PEASS-ng/releases/download/20220417/linpeas.sh
    dest: /opt/privesc

# Vars for Pip packages
python_pip_packages:
  - asyncua
  - BAC0
  - bacpypes
  - bloodhound
  - bokeh
  - capstone
  - cpppo
  - cython
  - ctmodbus
  - ctserial
  - donut-shellcode
  - mitm6
  - opcua-client
  - pandas
  - paramiko
  - pipenv
  - poetry
  - pycomm3
  - pyusb 
  - pycrypto
  - pylogix
  - pymodbus
  - pypykatz
  - pyserial
  - python-libpcap
  - python-snap7
  - pwntools
  - requests
  - roadrecon
  - ropper
  - unicorn

# Vars for gem installs  
ruby_gem_packages:
  - winrm
  - winrm-fs
  - stringio
  - evil-winrm

ufw_application_profiles:
  - responder

# Extensions for VS Code
vscode_extensions:
  # Language extensions
  - ms-python.python
  - ms-vscode.cpptools
  - ms-vscode.powershell
  # Utility extensions
  - esbenp.prettier-vscode
  
